- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: load cities data
  ansible.builtin.shell: "mysql -h mysql.lingaiah.online -uroot -p{{mysql_password}}  < /app/db/schema.sql"

- name: load cities data-2
  ansible.builtin.shell: "mysql -h mysql.lingaiah.online -uroot -p{{mysql_password}}  < /app/db/app-user.sql"
  
- name: load cities data-3
  ansible.builtin.shell: "mysql -h mysql.lingaiah.online -uroot -p{{mysql_password}}  < /app/db/master-data.sql"


# - name: check cities schema exists or not
#   ansible.builtin.command:  mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
#   register: schema

# - name: print output
#   ansible.builtin.debug:
#     msg: "schema output: {{schema}}"

# - name: load cities data
#   ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
#   when: schema.stdout != "1"